//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSV_Accounting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSV_Accounting.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string AndSeparator {
            get {
                return ResourceManager.GetString("AndSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Accounting File Maker.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Btn_About {
            get {
                return ResourceManager.GetString("Btn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        internal static string Btn_AddRow {
            get {
                return ResourceManager.GetString("Btn_AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a CSV file.
        /// </summary>
        internal static string Btn_ImportCsv {
            get {
                return ResourceManager.GetString("Btn_ImportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Table.
        /// </summary>
        internal static string Btn_OpenTable {
            get {
                return ResourceManager.GetString("Btn_OpenTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Btn_Redo {
            get {
                return ResourceManager.GetString("Btn_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As ....
        /// </summary>
        internal static string Btn_SaveAs {
            get {
                return ResourceManager.GetString("Btn_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Btn_Undo {
            get {
                return ResourceManager.GetString("Btn_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Accounting Terms.
        /// </summary>
        internal static string Checkbox_AccountingTerms {
            get {
                return ResourceManager.GetString("Checkbox_AccountingTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Col_Balance {
            get {
                return ResourceManager.GetString("Col_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Col_Credit {
            get {
                return ResourceManager.GetString("Col_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Col_Date {
            get {
                return ResourceManager.GetString("Col_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string Col_Debit {
            get {
                return ResourceManager.GetString("Col_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Col_Description {
            get {
                return ResourceManager.GetString("Col_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflow.
        /// </summary>
        internal static string Col_Inflow {
            get {
                return ResourceManager.GetString("Col_Inflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outflow.
        /// </summary>
        internal static string Col_Outflow {
            get {
                return ResourceManager.GetString("Col_Outflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Col_Reference {
            get {
                return ResourceManager.GetString("Col_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string Col_Tags {
            get {
                return ResourceManager.GetString("Col_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Col_Total {
            get {
                return ResourceManager.GetString("Col_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open calendar.
        /// </summary>
        internal static string DateTooltip {
            get {
                return ResourceManager.GetString("DateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format. Please input dd/MM/yyyy.
        ///(Example: 01/01/1997).
        /// </summary>
        internal static string Err_InvalidDate {
            get {
                return ResourceManager.GetString("Err_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        internal static string Err_InvalidInput {
            get {
                return ResourceManager.GetString("Err_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading CSV:.
        /// </summary>
        internal static string Err_Load {
            get {
                return ResourceManager.GetString("Err_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving: .
        /// </summary>
        internal static string Err_Save {
            get {
                return ResourceManager.GetString("Err_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is developed by Mochamad Adamrasyad Iqbal (C) 1444 H. The software is useful to make an accounting table whenever needed and open compatible CSV files..
        /// </summary>
        internal static string Lbl_AboutDesc {
            get {
                return ResourceManager.GetString("Lbl_AboutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Lbl_AboutTitle {
            get {
                return ResourceManager.GetString("Lbl_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string Lbl_Analytics {
            get {
                return ResourceManager.GetString("Lbl_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} expenses increased {1} over the last 3 months..
        /// </summary>
        internal static string Lbl_Desc {
            get {
                return ResourceManager.GetString("Lbl_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by tag:.
        /// </summary>
        internal static string Lbl_FilterByTag {
            get {
                return ResourceManager.GetString("Lbl_FilterByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Edited on: .
        /// </summary>
        internal static string Lbl_LastEdited {
            get {
                return ResourceManager.GetString("Lbl_LastEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened CSV .
        /// </summary>
        internal static string Lbl_OpenedCSV {
            get {
                return ResourceManager.GetString("Lbl_OpenedCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved to: .
        /// </summary>
        internal static string Lbl_SavedTo {
            get {
                return ResourceManager.GetString("Lbl_SavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File is successfully saved.
        /// </summary>
        internal static string Lbl_SaveSuccess {
            get {
                return ResourceManager.GetString("Lbl_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CSV Accounting File Maker.
        /// </summary>
        internal static string Lbl_Welcome {
            get {
                return ResourceManager.GetString("Lbl_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string ListSeparator {
            get {
                return ResourceManager.GetString("ListSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry.
        /// </summary>
        internal static string Log_DefaultDesc {
            get {
                return ResourceManager.GetString("Log_DefaultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You spent the most in {0} mostly on {1}..
        /// </summary>
        internal static string MaxSpendTags {
            get {
                return ResourceManager.GetString("MaxSpendTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm row deletion?.
        /// </summary>
        internal static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert number
        ///(Example: 150.50 or 100+50*2).
        /// </summary>
        internal static string Msg_InsertNumber {
            get {
                return ResourceManager.GetString("Msg_InsertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid math expression.
        ///(Example: Square(20) or Power(20,2) instead of 20^2).
        /// </summary>
        internal static string Msg_InvalidMathExpression {
            get {
                return ResourceManager.GetString("Msg_InvalidMathExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save before overwrite current ledger?.
        /// </summary>
        internal static string Msg_OverwriteCurrent {
            get {
                return ResourceManager.GetString("Msg_OverwriteCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save before closing?.
        /// </summary>
        internal static string Msg_SaveBeforeClosing {
            get {
                return ResourceManager.GetString("Msg_SaveBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current edited ledger will be overwritten and cannot be undone after open! Save before open? .
        /// </summary>
        internal static string Msg_SaveBeforeOpen {
            get {
                return ResourceManager.GetString("Msg_SaveBeforeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as CSV.
        /// </summary>
        internal static string Msg_SaveTitle {
            get {
                return ResourceManager.GetString("Msg_SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spending data found..
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by description, reference, or tags....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERALL TOTAL.
        /// </summary>
        internal static string StringGrandBalance {
            get {
                return ResourceManager.GetString("StringGrandBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded :.
        /// </summary>
        internal static string StringLoaded {
            get {
                return ResourceManager.GetString("StringLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTHLY TOTAL.
        /// </summary>
        internal static string StringMonthlyBalance {
            get {
                return ResourceManager.GetString("StringMonthlyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Click to filter by this tag.
        /// </summary>
        internal static string TagsTooltip {
            get {
                return ResourceManager.GetString("TagsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        internal static string Title_Delete {
            get {
                return ResourceManager.GetString("Title_Delete", resourceCulture);
            }
        }
    }
}
